name: Performance Testing - EXPLAIN Plan Capture

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop
    paths:
      - 'backend/**'
      - 'specs/**'
      - 'infra/github-actions/report-perf.yml'

jobs:
  explain-plans:
    name: Capture EXPLAIN Plans for Key Queries
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: reporting_perf_test
          POSTGRES_USER: perf_test
          POSTGRES_PASSWORD: perf_test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize PostgreSQL schema
        env:
          PGPASSWORD: perf_test_password
        run: |
          echo "Waiting for PostgreSQL..."
          timeout 30 bash -c 'until psql -h localhost -U perf_test -d reporting_perf_test -c "SELECT 1" 2>/dev/null; do sleep 1; done' || true
          echo "PostgreSQL is ready"
          
          # Create schema directory if it doesn't exist
          mkdir -p backend/ingestion/src/db/migrations
          
          # Initialize with basic schema (if migrations exist)
          if [ -f "backend/ingestion/src/db/migrations/001_init_schema.sql" ]; then
            psql -h localhost -U perf_test -d reporting_perf_test -f backend/ingestion/src/db/migrations/001_init_schema.sql || true
            echo "Schema initialized from migrations"
          else
            echo "No migrations found - creating minimal schema for testing"
            psql -h localhost -U perf_test -d reporting_perf_test << 'SCHEMA'
            CREATE TABLE IF NOT EXISTS accounts (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              name VARCHAR(255) NOT NULL,
              active BOOLEAN DEFAULT true,
              created_at TIMESTAMP DEFAULT NOW()
            );
            
            CREATE TABLE IF NOT EXISTS import_batches (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              account_id UUID REFERENCES accounts(id),
              batch_name VARCHAR(255) NOT NULL,
              created_at TIMESTAMP DEFAULT NOW()
            );
            
            CREATE TABLE IF NOT EXISTS classifiers (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              name VARCHAR(255) NOT NULL
            );
            
            CREATE TABLE IF NOT EXISTS transactions (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              account_id UUID REFERENCES accounts(id),
              classifier_id UUID REFERENCES classifiers(id),
              amount DECIMAL(15, 2),
              created_at TIMESTAMP DEFAULT NOW()
            );
            
            CREATE TABLE IF NOT EXISTS overrides (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              transaction_id UUID REFERENCES transactions(id),
              is_active BOOLEAN DEFAULT true,
              created_at TIMESTAMP DEFAULT NOW()
            );
            
            CREATE INDEX IF NOT EXISTS idx_accounts_active ON accounts(active);
            CREATE INDEX IF NOT EXISTS idx_import_batches_created ON import_batches(created_at);
            CREATE INDEX IF NOT EXISTS idx_transactions_account ON transactions(account_id);
            CREATE INDEX IF NOT EXISTS idx_transactions_created ON transactions(created_at);
            CREATE INDEX IF NOT EXISTS idx_overrides_active ON overrides(is_active);
SCHEMA
          fi

      - name: Capture EXPLAIN plans for key queries
        env:
          PGPASSWORD: perf_test_password
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: reporting_perf_test
          DB_USER: perf_test
        run: |
          mkdir -p .github/reports/explain-plans
          
          # Function to run EXPLAIN and save results
          run_explain() {
            local query=$1
            local filename=$2
            echo "Running EXPLAIN for: $query"
            psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} \
              -c "EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${query}" \
              > ".github/reports/explain-plans/${filename}.json" 2>&1 || true
          }
          
          # Key queries for EXPLAIN analysis
          echo "Capturing EXPLAIN plans for critical queries..."
          
          # Simple index scans
          run_explain "SELECT * FROM accounts WHERE active = true LIMIT 10" "01_accounts_active"
          run_explain "SELECT * FROM import_batches ORDER BY created_at DESC LIMIT 100" "02_import_batches_recent"
          
          # Joins with filter
          run_explain "SELECT t.*, c.name FROM transactions t LEFT JOIN classifiers c ON t.classifier_id = c.id WHERE t.created_at >= NOW() - INTERVAL '30 days' LIMIT 100" "03_transactions_classified_30d"
          
          # Aggregation
          run_explain "SELECT account_id, SUM(amount) as total FROM transactions WHERE created_at >= NOW() - INTERVAL '1 month' GROUP BY account_id" "04_transactions_monthly_summary"
          
          # Simple filter
          run_explain "SELECT * FROM overrides WHERE is_active = true ORDER BY created_at DESC LIMIT 50" "05_overrides_active"
          
          echo "EXPLAIN plans captured successfully"

      - name: Analyze EXPLAIN results
        run: |
          echo "## Performance Analysis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Query Execution Plans" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -d ".github/reports/explain-plans" ]; then
            for file in $(ls -1 .github/reports/explain-plans/*.json | sort); do
              filename=$(basename "$file")
              echo "- **${filename%.*}**: Plan captured" >> $GITHUB_STEP_SUMMARY
            done
          fi

      - name: Upload EXPLAIN plans as artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: explain-plans
          path: .github/reports/explain-plans/

  test-performance:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: reporting_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Spring Boot tests
        working-directory: backend/reporting
        run: |
          ./mvnw test -Dtest=RBACServiceTest 2>&1 | tee test-output.log || true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: backend/ingestion/package-lock.json

      - name: Run Node.js tests with coverage
        working-directory: backend/ingestion
        run: |
          npm install > /dev/null 2>&1 || true
          npm test 2>&1 | tee test-output.log || true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            backend/reporting/test-output.log
            backend/ingestion/test-output.log

  build-report:
    name: Build Performance Report
    runs-on: ubuntu-latest
    needs: [explain-plans, test-performance]
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download EXPLAIN plans
        uses: actions/download-artifact@v3
        with:
          name: explain-plans
          path: .github/reports/explain-plans
        continue-on-error: true

      - name: Generate performance report
        run: |
          mkdir -p .github/reports
          cat > .github/reports/PERFORMANCE_REPORT.md << 'EOF'
          # Performance Analysis Report
          
          ## Overview
          
          This report contains performance analysis including EXPLAIN ANALYZE plans for critical database queries.
          
          ## Key Metrics
          
          - **Query Execution Time**: Total time spent executing the query
          - **Planning Time**: Time spent on query planning
          - **Buffer Efficiency**: Cache hit vs disk I/O ratio
          - **Index Usage**: Whether indexes are being utilized effectively
          
          ## Performance Baselines
          
          | Query Type | Threshold |
          |-----------|-----------|
          | Point lookups (single row) | < 1ms |
          | Index range scans | < 100ms |
          | Aggregation queries | < 5000ms |
          | Join queries | < 2000ms |
          
          ## Recommendations
          
          1. **Monitor execution times** across commits to identify regressions
          2. **Review execution plans** to ensure indexes are being used
          3. **Analyze buffer statistics** to understand cache efficiency
          4. **Compare plans** across different PostgreSQL versions
          
          ## Captured Plans
          
          Plans are available in the `explain-plans` artifact.
          
          EOF
          echo "Performance report generated"

      - name: Comment on PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let comment = '## ðŸ“Š Performance Analysis Report\n\n';
            
            const planDir = '.github/reports/explain-plans';
            if (fs.existsSync(planDir)) {
              const files = fs.readdirSync(planDir).filter(f => f.endsWith('.json'));
              if (files.length > 0) {
                comment += `âœ… Captured ${files.length} EXPLAIN plan(s):\n\n`;
                files.forEach(file => {
                  comment += `- **${file}**: Available in artifacts\n`;
                });
              } else {
                comment += 'âš ï¸ No EXPLAIN plans were captured.\n';
              }
            } else {
              comment += 'âš ï¸ Plans directory not found.\n';
            }
            
            comment += '\n---\n';
            comment += '*Performance testing enabled. Download the artifacts to view detailed execution plans.*\n';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }).catch(err => console.log('Could not comment on PR:', err));

